### PR TITLE
Stutilnote 2 refactor notes

### PR DESCRIPTION
**Pull request by zburke**
Prep for refactoring the business logic of `<Notes>` into a separate repository, and a bug fix: re-render the new-note-form with updated props when the notes pane is left open and the selected-item, which sets the note's `link` prop, changes.

### CODE REVIEW

**Comment by MikeTaylor** [comment]
Zak, do you not have the permission to merge your own PRs? If not, we should fix that.

**Comment by zburke** [comment]
No worries. I do have the necessary permissions but was holding off until I had corresponding PRs ready to go in ui-users and mod-util-notes.

**Comment by MikeTaylor** [comment]
Oops -- then I spoiled your plan by prematurely accepting your PR! Sorry!

I guess in future it might not be a bad idea, in such circumstances, to add
a note to the PR description saying that it's not ready for merging.

I hope my hair-trigger problem doesn't cause you too much difficulty.

-- Mike.

**Comment by zburke** [comment]
Really, I should just be more patient and wait to PR my branches until I have them all lined up.

**Pull request merged**
