### PR TITLE
STCOM-517: Create common WYSIWYG editor

### PR DESCRIPTION
**Pull request by Godlevskyi**
## Purpose

The purpose of this PR is to create the reusable  WYSIWYG editor component. 
Currently it is planned to be used in the notes create/update forms.

This component wraps the react-quill library  (see https://github.com/zenoamaro/react-quill#the-unprivileged-editor) with label and validation controls.

## Approach

The react-quill library was used for the Editor and in the PR wrapped with with label and validation controls.
react-quill was chosen as the base  as is it has good support and stars on gitHub and also iut was used for in the circulation module.
 
#### TODOS and Open Questions
Add the preview functionality to apply it to the circulation module

## Screenshots
Screen Shot 2019-05-01 at 20 33 54

### CODE REVIEW

**Comment by JohnC-80** [comment]
@Godlevskyi Thank you for your work on this... is there a way to tab out of an editor once keyboard focus is within it? The tab key just enters more tab characters, and I can't seem to get out of / past the component.

**Comment by Godlevskyi** [comment]
> @Godlevskyi Thank you for your work on this... is there a way to tab out of an editor once keyboard focus is within it? The tab key just enters more tab characters, and I can't seem to get out of / past the component.

Thanks John! 
I managed to tab out using the Alt+Tab

**Comment by doytch** [comment]
I've got no issues with this, but am wondering why this is a stripes-smart-components component rather than just stripes-components. I was always under the impression that SSC was for connected components.

**Comment by Godlevskyi** [comment]
> I've got no issues with this from a code POV, but am wondering why this is a stripes-smart-components component rather than just stripes-components. I was always under the impression that SSC was for connected components.

Thanks Mark, you are right the task was originally created for the stripes-smart-components as a helper component for notes but then we decided to add it to stripes-components. As you can see this PR is for the stripes-components. 
Will ask Khalilah to move this ticket to STCOM in JIRA

**Comment by doytch** [comment]
🤣 So I guess apparently my walking pneumonia isn't fully gone...yeah, I totally just saw the issue code and didn't really see what repo I was in. My bad, sorry!

**Comment by Godlevskyi** [comment]
> 🤣 So I guess apparently my walking pneumonia isn't fully gone...yeah, I totally just saw the issue code and didn't really see what repo I was in. My bad, sorry!

No props! Thanks for reviewing and get well soon!

**Comment by JohnC-80** [comment]
`alt + tab` on windows is an OS shortcut for bringing up a windows switcher. Most other rich text editors just won't enable tabs in the formatting of the text, so the editor can be easily tabbed out of.

**Comment by Godlevskyi** [comment]
> `alt + tab` on windows is an OS shortcut for bringing up a windows switcher. Most other rich text editors just won't enable tabs in the formatting of the text, so the editor can be easily tabbed out of.

Hi John! Disabled editor tabbing by default.

**Pull request merged**
