### PR TITLE
STCOM-253 additional translations

### PR DESCRIPTION
**Pull request by rjruizes**
https://issues.folio.org/browse/STCOM-253
Follow up to #365, #368

### CODE REVIEW

**Comment by cherewaty** [comment]
@Robdel12 should all of these `title` attributes should be `ariaLabel`s instead?

**Comment by Robdel12** [comment]
Yeah titles shouldn’t be used anymore. @JohnC-80 how did you want to attack that? Piece by piece as PRs come through? I think even some of these airia labels can disappear too.

**Comment by JohnC-80** [comment]
There's still more work to do in other components in reducing the usage of `title`, but @rjruizes, if you would, go ahead and prefer `ariaLabel` on these changes for the buttons that are using icons. If a button contains text, both `ariaLabel` and `title` are unnecessary - is that in sync with your thinking, @Robdel12 ?
We'll have to figure out something to give us the tool-tip benefit that the `title` attribute provides at some point, but that's in the future...

**Comment by cherewaty** [comment]
@rjruizes thanks for trying to tackle the `componentWillReceiveProps` deprecations. Since that work involves highly volatile changes, could you split it out into a separate PR? That'd mean we can get the lower-risk internationalization work out quicker.

**Comment by rjruizes** [comment]
Yep, will do. I'm going to do one more component just to get the test to run again. The last one false negative.

**Pull request merged**
