### PR TITLE
STCOM-1101 Add `rootClass` and `fitContent` props to `<TextArea>`

### PR DESCRIPTION
**Pull request by BogdanDenis**
## Description
Add `rootClass` prop to be able to define custom styles for `<TextArea>` wrapper element
Add `fitContent` prop to be able to set initial width of `<TextArea>` to fit content

## Screenshots

https://user-images.githubusercontent.com/19309423/215756427-29c7e504-0572-4010-b9b6-fb439c73b15e.mp4

## Issues
[STCOM-1101](https://issues.folio.org/browse/STCOM-1101)

### CODE REVIEW

**Review by zburke — CHANGES_REQUESTED** [review]
I understand we don't already have a README.md for this component, but we do show several different options in the storybook in `stories/BasicUsage.js` so let's at least add an example there instead of digging the no-documentation hole any deeper. It would be great to write a quick README too, but I understand that's asking a lot given the small modifications you're making to this big component. 

As to the new props: it isn't immediately obvious how `fitContent` will differ from `fullWidth` so please make sure to explain this. Maybe it'll be obvious in the storybook UI, but just reading the description they sound similar. 

New props should be covered by new tests as well, i.e. making sure that the desired attributes are present in the DOM when the component receives these new props.

**Comment by zburke** [comment]
@BogdanDenis, FYI I filed https://issues.folio.org/browse/STCOM-1102 for adding a `README.md` since it's unfair to spring that requirement on this ticket.

**Comment by BogdanDenis** [comment]
Hey @zburke thanks for your comments - I've added some details on difference between `fitContent` and `fullWidth` in prop types declaration, as well as storybook examples and tests
Also, there's a change in `stripes-testing` that we need for tests https://github.com/folio-org/stripes-testing/pull/820

**Review by zburke — CHANGES_REQUESTED** [review]
Thanks for the documentation and tests! Given this relies on a new interactor in stripes-testing, that means we need to bump the minimum version of `@folio/stripes-testing` in the dev-deps to the version that includes that interactor. It looks like that'll be 4.5.0.

**Review by zburke — APPROVED** [review]

**Review by Dmytro-Melnyshyn — APPROVED** [review]

**Review by JohnC-80 — APPROVED** [review]

**Pull request merged**
