### PR TITLE
MultiSelect: Add `data-open` attr for ease of testing

### PR DESCRIPTION
**Pull request by doytch**
Sure, this looks dumb. 

But @MikeTaylor stumbled onto [this bit of information just now](https://github.com/folio-org/stripes-testing/blob/master/doc/nightmare.md#be-careful-with-multiselection) and I gotta admit, I don't love that [we have to write `:not([hidden])` here](https://github.com/folio-org/ui-inventory/pull/828/files#diff-85c813b2a76a618951639af498e3f0c9R65).

I don't want to break existing functionality obviously, so I'm just adding this attribute to be able to write selectors in a more lexically cogent manner.

### CODE REVIEW

**Comment by zburke** [comment]
@doytch, can you explain how this helps given `open` is not a [DOM attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes)?

**Comment by doytch** [comment]
@zburke, that list of attributes contains those have a standardized value format or purpose. You can throw any attribute you want on a DOM element. It can be `foobar-i-love-folio-this-much="a lot"` for all the browser cares.

For this purpose, given the absence of a semantically-appropriate attribute, I think we'd want something that is specifically _not_ on that list to make sure we don't collide with anything else.

**Comment by VictorSoroka1** [comment]
Since it is not in the specification, I would suggest data-open so we can be sure that it won't collide.

**Comment by zburke** [comment]
> I also see warnings from React when DOM element provided with an attribute which is not in the specification.

Yeah, React gets noisy on the console about this kind of thing. `data-open` works for me; good suggestion @VictorSoroka1.

**Comment by doytch** [comment]
Good point. For some reason I missed this warning...

Updated!

**Comment by MikeTaylor** [comment]
Yes, `data-open` is better. (Though that the HTML people were thinking in using such a generic prefix as `data-` for private extensions, I can't imagine. At least RFC 1822's `X-` prefix for non-standard email headers make it clear that they are extensions. I mean, isn't _everything_ data?)

Anyway: go ahead and merge, say I.

**Pull request merged**
