### PR TITLE
STCOM-1097: Add line break at newline characters in KeyValue component

### PR DESCRIPTION
**Pull request by OleksandrHladchenko1**
## Links
[STCOM-1097](https://issues.folio.org/browse/STCOM-1097)
[UIDATIMP-1342](https://issues.folio.org/browse/UIDATIMP-1342)

### CODE REVIEW

**Comment by zburke** [comment]
@OleksandrHladchenko1, do we have an example of the display problem this PR resolves? Sorry, it isn't clearly articulated in any of the linked tickets.

**Comment by JohnC-80** [comment]
@OleksandrHladchenko1 perhaps just a before/after screenshot with the change in place? I think I understand they want to render multiline values - like addresses - correctly. Thank you!

**Comment by OleksandrHladchenko1** [comment]
> 

Hi @zburke I think the problem is displayed in this PR https://github.com/folio-org/ui-data-import/pull/1314.

**Comment by OleksandrHladchenko1** [comment]
> @OleksandrHladchenko1 perhaps just a before/after screenshot with the change in place? I think I understand they want to render multiline values - like addresses - correctly. Thank you!

Hi @JohnC-80 We get the address from backend as `"Acquisitions Staff Accountant \nTexas A&M University Libraries \n5000 TAMU \nCollege Station, TX   77843-5000"` and we need to display this address as
image

When I added `white-space: pre-wrap` to the `KeyValue` component, it started to see newline breaks and render the address as expected

>

**Review by JohnC-80 — APPROVED** [review]

**Review by zburke — CHANGES_REQUESTED** [review]
Gotcha; thanks for the clarification. The code change is fine, but we need to update `readme.md` with a note that whitespace in the `value` prop will be honored since this is 100% contrary to how it ordinarily works. Breaking the rules is fine, as long as you do it knowingly and loudly.

**Review by zburke — APPROVED** [review]
LGTM! Thank you. Sorry; I know that was pedantic of me

**Pull request merged**
