### PR TITLE
Uiu 382 permissionset

### PR DESCRIPTION
**Pull request by aditya-matukumalli**

### CODE REVIEW

**Comment by cherewaty** [comment]
@aditya-matukumalli since this is only a single line change, can you squash the commits into one to streamline the git history?

**Comment by aditya-matukumalli** [comment]
@cherewaty Yes, The fix is currently under review. I will squash it while merging the branch.

**Comment by cherewaty** [comment]
Looks like something went wrong with a rebase here. You were added as a committer to over a dozen duplicate commits that weren't part of this PR. Please ensure you have a clean git history next time before merging.

FOLIO best practices: https://dev.folio.org/community/contrib-code/

**Comment by aditya-matukumalli** [comment]
Oh, thats weird. Yeah, I will make sure this doesn't happen again. Thanks

**Pull request merged**
