### PR TITLE
Added an icon-prop to the NavListItem

### PR DESCRIPTION
**Pull request by rasmuswoelk**
Passing an icon as a strong to the NavListItem will render an `<Icon>` next to the label.

image

image

### CODE REVIEW

**Comment by cherewaty** [comment]
I have doubts that we want to design icons for every possible thing that could appear in that menu, but this implementation looks good 👍

**Comment by JohnC-80** [comment]
I have similar concerns, @cherewaty .
@rasmuswoelk Would `<NavListItems>` without icons in the same list still be completely left-aligned?

**Comment by rasmuswoelk** [comment]
@JohnC-80 @cherewaty 

After submitting it I did think about whether or not this was the correct approach. You can achieve the same thing by passing an `<Icon>` to the an list item.

The reasoning behind having it as prop was to make it easier for devs to add an icon since I expect that it will be a fairly repeated design pattern across the system (judging from prototypes).

It's of course completely optional and any ListItems without icons are untouched by this change.

**Comment by JohnC-80** [comment]
I think a design situation that's to-be-considered is this, when not ALL of the menu items have an icon associated with them: there's both an alignment issue and a design issue: 
Example: an icon missing, menu-item goes full-left-align, out of alignment with the rest.
image

A possible way, but would add default padding or some sort of spacer to all items if they didn't have an icon (possibly not ideal either)
image

@filipjakobsen @rasmuswoelk

**Comment by rasmuswoelk** [comment]
@JohnC-80 Hmm. I guess if you don't have icons for all items in a list, you would not use icons in any of the items. And vice versa.

But since this can be achieved by simply passing an `<Icon>` to a `<NavListItem>` currently I will close this issue.

**Pull request closed without merging**
