### PR TITLE
fix icon plus size and add document  icon

### PR DESCRIPTION
**Pull request by cchiama**
fix icon plus size and add document  icon

### CODE REVIEW

**Comment by rasmuswoelk** [comment]
I think we'll rename any icons without whitespace to have a suffix of `inline` which indicates that it should be used inline with text. E.g. `icon-plus-inline` (without whitespace) and `icon-plus` (with whitespace).

We would need to update documentation and replace icons in various places while doing so to avoid "breaking" anything. 

So for now, could we just add the new document icon and leave the re-sizing of the plus-icon out of this PR?

**Comment by rasmuswoelk** [comment]
@cchiama

**Comment by cchiama** [comment]
Hi @rasmuswoelk

**Comment by rasmuswoelk** [comment]
@cchiama Looks good!

I was wondering if "document" would be a more fitting icon name than "report"?

**Comment by be-engineering** [comment]
> @cchiama Looks good!
> 
> I was wondering if "document" would be a more fitting icon name than "report"?

I agree with you @rasmuswoelk

**Comment by cchiama** [comment]
I agree with you @rasmuswoelk

**Comment by cherewaty** [comment]
With https://github.com/folio-org/stripes-components/pull/674 merged...
- we can remove `down-caret-inline` and `up-caret-inline`
- resize `document` to 32x32

... and this'll be shippable 🚀

**Comment by cchiama** [comment]
Hi @rasmuswoelk i made a unique change, on document icon and i cannot made change on the icon plus, as request in above comments. The PR can be merge if you want.

**Comment by cherewaty** [comment]
Sorry to keep moving the target @cchiama - we've made a lot of changes here recently. All the other icons now have a `viewBox` of `"0 0 32 32"`.

**Comment by cchiama** [comment]
fix EOL lint error @rasmuswoelk.

**Comment by rasmuswoelk** [comment]
@cchiama 

I think the last thing that needs to be updated is the viewBox. As @cherewaty mentioned above the viewBox should be `viewBox="0 0 32 32"`

It should be mergeable after this small change 👍

**Comment by cherewaty** [comment]
Looks like you resized the `viewBox` but didn't scale the shape itself, so it's a lot smaller than other icons: 
screen shot 2018-12-03 at 1 14 27 pm

**Comment by cherewaty** [comment]
Resolved with https://github.com/folio-org/stripes-components/pull/760

**Pull request closed without merging**
