### PR TITLE
STCOM-460: Fixed "closeOnBackgroundClick" behaviour for <Modal> 

### PR DESCRIPTION
**Pull request by rasmuswoelk**
## Ticket
https://issues.folio.org/browse/STCOM-460

### CODE REVIEW

**Comment by rasmuswoelk** [comment]
@JohnC-80 We already have tests in place that checks if the `onClose`-callback runs when the overlay is clicked and the `closeOnBackgroundClick`-prop is `true`. Should I add a test for the opposite? 🤔

**Comment by JohnC-80** [comment]
Clicking when `closeOnBackgroundClick` is falsey/undefined? The more coverage the better. The un-covered branches of statements can add up.

**Comment by rasmuswoelk** [comment]
@JohnC-80 Yes. I'll add a test for it 👍

**Comment by rasmuswoelk** [comment]
@JohnC-80 I added the test

**Pull request merged**
