### PR TITLE
Fix MCL README onResetMark/onMarkReset typo and alphabetization

### PR DESCRIPTION
**Pull request by ncovercash**
[The code](https://github.com/folio-org/stripes-components/blob/master/lib/MultiColumnList/MCLRenderer.js#L222) references `onMarkReset` rather than `onResetMark`; this PR updates the README accordingly.

### CODE REVIEW

**Comment by ncovercash** [comment]
Also, I can't seem to find anywhere `sortedClass` is actually implemented, grepping the entire `stripes-components` codebase shows no results but I wanted to ask here before proposing that be removed from the README.

**Comment by JohnC-80** [comment]
Thanks @ncovercash Looks like the docs for `sortedClass` were written first, then the functionality just settled on complete inversion afterward. It's fine to remove from documentation.

**Comment by ncovercash** [comment]
@JohnC-80 done

**Review by JohnC-80 — APPROVED** [review]

**Comment by JohnC-80** [comment]
merged in #1893

**Pull request closed without merging**
