### PR TITLE
New document for discussion: parameterizing-makeQueryFunction

### PR DESCRIPTION
**Pull request by MikeTaylor**

### CODE REVIEW

**Comment by JohnC-80** [comment]
For convenience, the rendered markdown: https://github.com/folio-org/stripes-components/blob/discussion-of-parameterizing-makeQueryFunction/util/parameterizing-makeQueryFunction.md

I'm fine with this change to make the utility more generic. Hopeful for more feedback from others who have possibly set something like this up @zburke @Baroquem @mkuklis

**Comment by mkuklis** [comment]
@MikeTaylor @JohnC-80 I haven't touched `makeQueryFunction` before but the proposed change (adding extra `params` argument) to define the prefix looks like a good approach and it would allow us to move forward and hopefully help UNAM team to merge their work.

**Comment by MikeTaylor** [comment]
Thanks for the positive comments, folks. I don't know why this PR is failing tests -- in fact, I don't see how it _can_ given that the previous commit was good, since the only change is the addition of a document -- but I guess it doesn't matter so long as we can read it.

**Comment by cherewaty** [comment]
This fixed the tests: https://github.com/folio-org/stripes-components/pull/417 if you can get Jenkins to re-run, it should probably be good.

**Comment by MikeTaylor** [comment]
Thanks. I guess I'll find a typo somewhere and push another commit :-)

**Comment by MikeTaylor** [comment]
Duh, I forgot to merge the changes from `master`. Trying again.

**Comment by zburke** [comment]
FYI, closing and reopening a PR will also trigger Jenkins to re-run, even absent a new commit.

**Comment by MikeTaylor** [comment]
Thanks, well worth knowing!

**Pull request merged**
