### PR TITLE
Converted MetaSection to new interactors

### PR DESCRIPTION
**Pull request by ryandberger**
- Also updated MetaSection.test
- This will also be used by `StripesSmartComponents` `ViewMetaData-test`

### CODE REVIEW

**Review by zburke — APPROVED** [review]

**Comment by ryandberger** [comment]
Will hold off on merging for now since a number of `stripes-smart-components` tests directly reference `MetaSectionInteractor`, so will need to update those calls and merge lock-step with this PR.

**Comment by JohnC-80** [comment]
This interactor should probably be in stripes-testing. If this one is replaced it may break existing tests that use the old interactor.

**Review by JohnC-80 — CHANGES_REQUESTED** [review]
See my last comment... Another repo added to a multi-repo PR, I know..

**Comment by ryandberger** [comment]
> This interactor should probably be in stripes-testing. If this one is replaced it may break existing tests that use the old interactor.

Makes sense. Will do that!

**Comment by ryandberger** [comment]
> > This interactor should probably be in stripes-testing. If this one is replaced it may break existing tests that use the old interactor.
> 
> Makes sense. Will do that!

See: https://github.com/folio-org/stripes-testing/pull/232

**Comment by zburke** [comment]
@ryandberger , what's the status with this PR? It looks like there was a conversation about leaving the existing interactor alone and updating tests to import a new one from stripes-testing. We did create the new interactor in folio-org/stripes-testing/pull/232, but maybe we didn't finish reverting the interactor here. 

Should this be closed or update?

**Review by JohnC-80 — APPROVED** [review]

**Comment by ryandberger** [comment]
> use update interactor from stripes-testing

@JohnC-80, made the update to use the metasection interactor from stripes-testing, so I will plan to merge now that this has been cleaned up.

**Pull request merged**
