### PR TITLE
Fix tests for interactors 1.0

### PR DESCRIPTION
**Pull request by wKich**
`@interactors/html` is prepping for the 1.0 release. This fixes some usages that were broken

### CODE REVIEW

**Review by JohnC-80 — APPROVED** [review]
Thank you @wKich for these changes and for the help shoring us up in https://github.com/folio-org/stripes-testing/pull/148

**Comment by JohnC-80** [comment]
Checked out these files/changes into a branch and set up #1692 
Well.. that's one way to get the changes in since this Sonar-cloud scan issue is a mystery...

**Comment by zburke** [comment]
@JohnC-80 , the sonarcloud scan mystery is explained in [FOLIO-3290](https://issues.folio.org/browse/FOLIO-3290) and unfortunately won't be fixed. Your workaround of pulling down the forked repo's branch and pushing it back to origin is, in fact, [The Official Way of dealing with branches on forks](https://dev.folio.org/guidelines/github-actions-frontend/#forked-repositories).

**Review by zburke — APPROVED** [review]

**Comment by JohnC-80** [comment]
Closing this guy, since we got all the changes merged in #1692

**Pull request closed without merging**
