### PR TITLE
STCOM-974: Add <Select> option background-color for FF

### PR DESCRIPTION
**Pull request by ncovercash**
# [Jira](https://issues.folio.org/browse/STCOM-974)

Currently, in Firefox, `<Select>` dropdowns are styled with `color: black;`.  However, Firefox's default UA stylesheet uses a dark background and light text color, therefore, when `color: black` is added, the dropdown is nearly unreadable:
image

This behavior is only present in Windows versions of Firefox -- on macOS, iOS, etc., a system dropdown is used, overriding any custom styling.  On Windows, Chrome and Edge similarly fully override dropdown colors.

This PR adds an explicit rule stating that `<option>` background colors should be white, which aligns with the way Chrome, etc. display dropdowns themselves, providing a more consistent experience and fixing this bug.

Here it is with the fix:
image

_(The solid-grey option is controlled by Firefox, and reflects whichever option currently has hover.  Other browsers have similar systems (usually in blue), so this default behavior is fine.)_

I've tested this across Edge, Chrome, and Firefox on Windows; Chrome, Safari, and Firefox and macOS; as well as in Safari on an iPad, and all select boxes render as expected.  I'm aware that Firefox is not officially supported by FOLIO, however, adding this in has no negative drawbacks (and may be beneficial in the future if any other browsers add additional styling support to select options, like Firefox did).

### CODE REVIEW

**Comment by ncovercash** [comment]
@JohnC-80 would you please review this?

**Review by JohnC-80 — APPROVED** [review]
Thanks @ncovercash

**Review by zburke — CHANGES_REQUESTED** [review]
I think we'd be better off referencing `var(--bg)` which is [defined as `#fff`](https://github.com/folio-org/stripes-components/blob/2e730cf0e65deead84ede66658483f98eb233dda/lib/variables.css#L24).

If we do want a local definition, please explain why in the PR description or better yet, in a comment in the CSS, and please use `#fff` to be consistent with other definitions.

**Comment by ncovercash** [comment]
@zburke fixed, thank you

**Review by zburke — APPROVED** [review]
LGTM

**Comment by zburke** [comment]
#1776 🇺🇸 🇺🇸 🇺🇸

**Pull request closed without merging**
