### PR TITLE
add hidden filter config. Refs UIU-400

### PR DESCRIPTION
**Pull request by zburke**
Allow filters to have hidden configuration values. For example, suppose
a filter group "species" existed and the query should *always* include
humans and allow the user to choose whether Ewok, Jawa, or Wookie
members should also be included in the search. Ewok, Jawa, and Wookie
would be included in the "values" array of the config element with
name: "species" and Human would be included in the array of the
hiddenConfig element keyed by "species".

Refs [UIU-400](https://issues.folio.org/browse/UIU-400)

### CODE REVIEW

**Comment by MikeTaylor** [comment]
Can you easily show me how the config looks for your ewok example?

**Comment by zburke** [comment]
```
// filters exposed to user as checkboxes
const filterConfig = [
  {
    label: 'Species',
    name: 'active',
    cql: 'active',
    values: [
       { name: 'Ewok', cql: 'ewok-unique-id' },
       { name: 'Jawa', cql: 'jawa-unique-id' },
       { name: 'Wookie', cql: 'wookie-unique-id' },
    ],
  },
];

// filters that are ALWAYS applied and that the user cannot control
const hiddenFilterConfig = {
  species: [
    { name: 'Human', cql: 'human' },
  ]
};
```

**Comment by MikeTaylor** [comment]
Why not just
```
const filterConfig = [
  {
    label: 'Species',
    name: 'active',
    cql: 'active',
    values: [
       { name: 'Ewok', cql: 'ewok-unique-id' },
       { name: 'Jawa', cql: 'jawa-unique-id' },
       { name: 'Wookie', cql: 'wookie-unique-id' },
       { name: 'Human', cql: 'human', hidden: true },
    ],
  },
];
```
?

**Comment by MikeTaylor** [comment]
Thank you. I suspect that once you have it in place, you'll find that the code delta is smaller, too.

BTW., don't forget to update `lib/FilterGroups/readme.md` when the code has settled.

**Pull request merged**
