### PR TITLE
Add <Spinner> from stripes-erm-components

### PR DESCRIPTION
**Pull request by MikeTaylor**
This is a simple copy-job, so my non-ERM app doesn't have to include stripes-erm-components.

### CODE REVIEW

**Comment by doytch** [comment]
I saw that @JohnC-80 has a big-ole spinner that he uses in the Users app. Could we support his use case via a prop?

**Comment by MikeTaylor** [comment]
That would be fine by me: whatever the official way of getting a spinner
is, I'll happily use it. I just don't want my non-ERM app to be dependent
on ERM.

**Comment by MikeTaylor** [comment]
BTW., does anyone understand what this ESLint error is complaining about?
```
/home/jenkins/workspace/o-org_stripes-components_PR-1091/project/lib/Spinner/Spinner.js
2:10  error  Icon not found in '../Icon'  import/named
```

The relevant line is https://github.com/folio-org/stripes-components/pull/1091/commits/d2f5f347c8266c6e39a4703990e61c0480c40884 and I can't for the life of me see what it supposed to be wrong with `import { Icon } from '../Icon'`.

**Comment by doytch** [comment]
> BTW., does anyone understand what this ESLint error is complaining about?
> 
> ```
> /home/jenkins/workspace/o-org_stripes-components_PR-1091/project/lib/Spinner/Spinner.js
> 2:10  error  Icon not found in '../Icon'  import/named
> ```
> 
> The relevant line is [d2f5f34](https://github.com/folio-org/stripes-components/commit/d2f5f347c8266c6e39a4703990e61c0480c40884) and I can't for the life of me see what it supposed to be wrong with `import { Icon } from '../Icon'`.

@MikeTaylor, it should be `import Icon from '../Icon'`, no? You're importing from the index.js of that directory which is `export default`ing.

**Comment by MikeTaylor** [comment]
(Closed and re-opened in the forlorn hope that this will trigger the stupid stupid stupid CLA check.)

**Comment by MikeTaylor** [comment]
All right, this is finally ready to merge.

Unless someone has a completely different approach to Spinner centralisation that they want to propose instead. But if so, please can it be quickish? :-)

**Comment by MikeTaylor** [comment]
OK, folks, can we merge this? @JohnC-80 @doytch @zburke.

**Pull request merged**
