### PR TITLE
STCOM 66 delete confirmation

### PR DESCRIPTION
**Pull request by JohnC-80**
This contains 2 significant additions to our toolset.
A) An alert pop-up component (`<Callout>`) that's super-easy to use and nicely accessible.
B) A reusable confirmation modal component for all of those 'Yes' or 'No' (or 'Submit' or 'Cancel') scenarios.
Submitted for approval!

### CODE REVIEW

**Comment by MikeTaylor** [comment]
@JohnC-80 Are you asking for an actual review of this code (in which case it will have to wait), or merely for me to click the "Yes, let John merge his code" button (which I can do now)?

**Comment by nielserik** [comment]
Oh, sorry, missed your question to John, @MikeTaylor, when ahead and approved.

**Comment by MikeTaylor** [comment]
Easily done! No matter, if @JohnC-80 wants an actual review he can just ask for it in the comments before he goes ahead and merges.

**Comment by JohnC-80** [comment]
Sorry for confusion there, guys...  I suppose my ceremonial verbiage got ahead of me. Only a 'fake' review was necessary for this... Merging away!

**Pull request merged**
